return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile" },
    dependencies = {
        "nvim-treesitter/nvim-treesitter-textobjects",
        "nvim-treesitter/nvim-treesitter-context",
    },
    opts = {
        ensure_installed = {
            "asm",
            "bash",
            "c",
            "cmake",
            "cpp",
            "csv",
            "diff",
            "dockerfile",
            "fish",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "hcl",
            "html",
            "json",
            "kdl",
            "latex",
            "lua",
            "luadoc",
            "make",
            "markdown",
            "markdown_inline",
            "python",
            "query",
            "regex",
            "ron",
            "rust",
            "ssh_config",
            "toml",
            "tsv",
            "typst",
            "vim",
            "vimdoc",
            "xml",
            "yaml",
        },
        sync_install = true,
        auto_install = true,
        ignore_install = {},
        highlight = { enable = true, },
        indent = { enable = true },
        textobjects = {
            select = {
                enable = true,
                lookahead = true,
                keymaps = {
                    ["ie"] = "@assignment.inner",
                    ["ae"] = "@assignment.outer",
                    ["le"] = "@assignment.lhs",
                    ["re"] = "@assignment.rhs",
                    ["aa"] = "@parameter.outer",
                    ["ia"] = "@parameter.inner",
                    ["ai"] = "@conditional.outer",
                    ["ii"] = "@conditional.inner",
                    ["af"] = "@function.outer",
                    ["if"] = "@function.inner",
                    ["ac"] = "@class.outer",
                    ["ic"] = "@class.inner",
                    ["al"] = "@loop.outer",
                    ["il"] = "@loop.inner",
                    ["at"] = "@comment.outer",
                    ["ad"] = "@documentation.outer",
                },
            },
            swap = {
                enable = true,
                swap_next = {
                    ["<leader>sn"] = "@parameter.inner",
                },
                swap_previous = {
                    ["<leader>sp"] = "@parameter.inner",
                },
            },
        },
    },
}
