# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
# The minimal, blazing-fast, and infinitely customizable prompt
# https://starship.rs

format = """
$time\
$username\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$python\
$conda\
$character"""

add_newline = false

[line_break]
disabled = true

[character]
success_symbol = "[](green)"
vimcmd_symbol = "[V](bold green) "
error_symbol = "[](red)"

[time]
disabled = false
format = "[$time]($style) "
style = "bright black"

[fill]
symbol = " "

[directory]
truncation_length = 5
style = "bold blue"

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
# style = "bright-black"
 
[git_state]
disabled = false

[git_status]
disabled = true
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_metrics]
disabled = true

[golang]
format = '[ $version](bold blue) '

[conda]
format = "[$symbol$environment]($style) "
style = "dimmed green"
ignore_base = true

[python]
symbol = " "
format = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
python_binary = ['./env/bin/python', './venv/bin/python', 'python', 'python3']

[typst]
format = "via [$symbol($version )]($style)"
